// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	UserID      uuid.UUID `json:"user_id"`
	HashedToken string    `json:"hashed_token"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type Report struct {
	UserID               uuid.UUID          `json:"user_id"`
	ID                   uuid.UUID          `json:"id"`
	ReportType           string             `json:"report_type"`
	OutputFilePath       pgtype.Text        `json:"output_file_path"`
	DownloadUrl          pgtype.Text        `json:"download_url"`
	DownloadUrlExpiresAt pgtype.Timestamptz `json:"download_url_expires_at"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	CreatedAt            time.Time          `json:"created_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FailedAt             pgtype.Timestamptz `json:"failed_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
