// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

type CreateUserRow struct {
}

func (q *Queries) CreateUser(ctx context.Context) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i CreateUserRow
	err := row.Scan()
	return i, err
}
